openshift/os

Jenkinsfile.rdgo

Add yet another Jenkins pipeline `Jenkinsfile.overlay` for rdgo built
packages.

Add a rdgo pipeline

---

Jenkinsfile.rdgo

The sync out was missing credentials for the rsync function and also
fixed a typo with the UserKnowHostsFile.

Add credentials to sync out

---

Jenkinsfile.rdgo
host-base.json
rhcos-continuous.repo

These are based on the git master of various projects and thus should
just be made public for easier consumption.

rdgo: Publish repo to S3

---

Jenkinsfile.treecompose

This is why the db diff was still failing.

treecompose: Trim commit string

---

Jenkinsfile.cloud

See individual commit messages for details.

cloud: Minor prep patches

---

Jenkinsfile.cloud
Jenkinsfile.treecompose

Follow up to #44 and #45. See individual commit messages for details.

cloud: Add more tags to AMI and snapshot

---

Jenkinsfile.treecompose

This got mixed up by the conflicts when merging.

treecompose: Fix provision/check ordering

---

host.yaml

See https://pagure.io/fedora-atomic/c/765bcdcab00eadffd83c29870b9459be0f39f76a?branch=master

manifest: Add podman

---

Jenkinsfile.cloud

See commit messages for details.

cloud: Fix file path and use coreos-assembler container

---

Jenkinsfile.cloud
Jenkinsfile.oscontainer
Jenkinsfile.rdgo
Jenkinsfile.treecompose
pipeline-utils.groovy

Add a separate groovy file and factor out a few useful functions common
to multiple pipelines.
This is more of an `#include` type thing rather than a Jenkins pipeline
shared library[1]. It doesn't feel like it's quite worth it yet.
[1] https://jenkins.io/doc/book/pipeline/shared-libraries/

Add pipeline-utils.groovy local lib

---

cloud.ks
host.yaml
overlay.yml

- disable rdgo for ignition for now
- add boot args for ignition
- target just ec2 for now

Attempt to get ignition working in stream

---

cloud.ks

Did some rudimentary logic in the dracut modules for now.

Remove harcoding of EC2 target

---

Jenkinsfile.cloud

Closes: https://github.com/openshift/os/issues/82

Jenkinsfile.cloud: Write AMI json to images directory

---

Jenkinsfile.rdgo
Jenkinsfile.treecompose

rdgo triggers treecompose, treecompose triggers cloud.

jenkins: Add triggers between jobs

---

overlay.yml

Signed-off-by: Steve Milner <smilner@redhat.com>

Add pivot in rdgo

---

README.md
host.yaml

Include pivot

---

cloud.ks
host.yaml

See https://github.com/openshift/os/pull/109#issuecomment-397651647.
(Untested).

cloud.ks: Add core user to some groups

---

overlay.yml

rdgo: Build cri-tools

---

host.yaml

host.yaml: Add cri-tools

---

Jenkinsfile.cloud

Not sure if there's a better way, open to suggestions

Jenkinsfile.cloud: start producing QEMU image

---

Jenkinsfile.cloud

Minor regression from #130. Also now start doing `sha256sum` for the new
qcow image.

cloud: Fix sha256sum generation

---

compose-post.sh

See https://bugzilla.redhat.com/show_bug.cgi?id=1594984

compose-post: Remove readahead

---

compose-post.sh

Let's give title + info/bug links.  CL today has a small motd; they
also changed to move it to `/run` which is a good idea.

post: Tweak /etc/motd

---

cloud.ks

This is part of https://github.com/dustymabe/ignition-dracut/pull/12

cloud.ks: Add $coreos_firstboot karg, create /boot/coreos-firstboot

---

Dockerfile.rollup.in
README.md
index.html
rollup.sh

This broke when reworking things earlier in ffbc3285b757ebc10e71b7dced04172cbd964ab1

Dockerfile: Fix nginx root

---

Jenkinsfile.cloud

Not prep for anything, just a drive by.

jenkins/cloud: Dedup dependency package list

---

Makefile
README-development.md

This will automatically redirect to a close mirror.

Makefile: Use download.fp.org for mirrors

---

Makefile

This is how I do my builds locally.

Makefile: Support include from out-of-tree

---

Jenkinsfile.treecompose

Need to define during assignment or bad things happen.

treecompose: define the ostree_version variable

---

Jenkinsfile.cloud

Uploading to AWS takes 20 minutes.  It's worth our while making
sure that the qcow2 boots and does something before we undertake that.

jenkins/cloud: Run a basic (15 second) kola rhcos.basic test

---

Dockerfile
rhcos-continuous.repo

We have to neuter the Dockerfile as we're not syncing that repo
out yet, and I don't remember where the code is for that.
This inside-and-outside problem is really awful.

Fix rdgo location

---

Jenkinsfile.cloud
Jenkinsfile.treecompose
host.yaml

Avoid duplicating things in the pipeline in prep for making the pipeline
more generic.

jenkins: Read ref and version from manifest file

---

Jenkinsfile.cloud
Jenkinsfile.rdgo
Jenkinsfile.treecompose
pipeline-utils.groovy

utils: Add helper to run assembler

---

Jenkinsfile.treecompose

Big shout out to @ashcrow for finding this syntax error causing jenkins to fail.

remove extra quote

---

Jenkinsfile.treecompose

Otherwise we will be reading a older version or another branch.
This bit me when doing some testing.

treecompose: Read manifest after checkout

---

Jenkinsfile.treecompose
Makefile
host-base.yaml
host-maipo.yaml

Prep for adding ootpa.  Split off a `host-base.yaml` that
contains things common to both, and rename the manifest to
`host-maipo.yaml`.

Split host into base + maipo

---

Jenkinsfile.rdgo
Jenkinsfile.treecompose

jenkins: Consistently use rhcos jenkins

---

Jenkinsfile.cloud
compose-post.sh

jenkins/cloud: Fix manifest reference

---

Jenkinsfile.treecompose
scripts/pull-mount-oscontainer

Prep for adding ootpa; we can more easily reuse it in multiple
pipelines.

jenkins: Refactor treecompose oscontainer pull to script

---

Jenkinsfile.cloud

Fix wrong aws json location

---

pipeline-utils.groovy

Remove --delete as it is a directory flag.

Fix file rsync flag

---

Jenkinsfile.aws-test

Speed up aws tests

---

Jenkinsfile.treecompose-ootpa

jenkins/ootpa: Sync changes from maipo job

---

rhel.repo

Switches repos from `7.5` :arrow_right: `7Server`.
Closed #269

rhel.repo: Switch to 7Server

---

.prow.sh
Makefile

Now that we mostly work in YAML files rather than JSON, let's adapt our
checks accordingly.

ci: Also syntax check YAML files

---

host-maipo.yaml
rdgo/overlay.yml

Drop docker from compose

---

Jenkinsfile.cloud

TODO: Replace this whole pipeline with assembler.

cloud: Switch to use sda2 for root

---

maipo.repo

maipo: Revert to released content

---

RELEASE.txt

This should help us make our releases more consistent and also
add instructions for what to do when things get more complex.

RELEASE: Add RELEASE.txt file for instructions

---

README.md

This reflects current reality better.

README.md: Update with better info

---

FAQ.md

Let's start answering things in public and in git.
See also https://github.com/openshift/machine-config-operator/pull/1165

FAQ.md: new file

---

FAQ.md

FAQ: Stub out networking vs FCOS

---

FAQ.md

FAQ.md: Link ifcfg PR

---

FAQ.md

Add OS update FAQ

---

FAQ.md

I'm going to start linking this a lot.

FAQ: Add CoreOS question

---

FAQ.md

FAQ: Add an Ignition debugging section

---

FAQ.md

Flesh things out a bit more based on discussions in
https://github.com/openshift/os/pull/396.

FAQ: Add more info about creating RHCOS AMIs

---

FAQ.md

Let's show how to get the RHCOS version; motivated by
finding the RHEL version.

faq: Add inspecting version

---

FAQ.md

This has been asked a few times.

FAQ: Which RHEL when

---

FAQ.md

This is common enough I think we should explicitly write it out.

FAQ: Add an 8.2 status section

---

README.md
docs/faq.md

This should help increase visibility for the official support option.

docs: Move support entry higher in the FAQ & README

---

docs/building.md
docs/faq.md

Now that the source is on GH we can say so!  While we're here
let's enhance the building docs.

FAQ: Link to building.md and enhance it

---

overlay.d/05rhcos/usr/libexec/rhcos-upgrade-root-filesystem-container

Address some comments that came after the original PR was queued to
merge.

rhcos-upgrade-root-filesystem-container: address comments

---

oscontainer.yaml

I intended this to be in the previous commit but in the grand
tradition of software engineering, I forgot `git add`.

oscontainer.yaml: Actually add this file

---

tests/kola/misc-ro/misc-ro.sh

Will keep us reminded of any actions we need to take when
NetworkManager changes.

tests/kola: add NetworkManager version check

---

ci/build-test.sh

I think *finally* all the pieces are together for this.
Closes: https://github.com/openshift/os/issues/417

ci/build-test: Do a cosa build + test

---

docs/faq.md

This came up a few times already.

faq: add entry about multipath

---

README.md
docs/development.md
docs/faq.md

docs/development: Also describe updating FCOS

---

ci/build-test-qemu.sh

Now that we have a better story for build extensions along side the
OS, let's start doing that as part of our CI.

ci: build extensions

---

overlay.d/05rhcos/usr/lib/systemd/system-preset/45-rhcos-extensions.preset

This is part of https://github.com/openshift/enhancements/pull/677
https://bugzilla.redhat.com/show_bug.cgi?id=1941342

overlay: Add 45-rhcos-extensions.preset

---

ci/build-test-qemu.sh
manifest.yaml
rhcos-packages.yaml
tests/kola/misc-ro/misc-ro.sh

Collection of small changes to move to RHEL 8.4.

Update for RHEL 8.4 Beta

---

docs/faq.md

In prep for getting this into product docs.

faq: Link to `single` docs from FCOS

---

docs/faq.md

Since it will have 4.6 and below vs 4.7+ bits.

faq: Link to portal solution

---

OWNERS

Goodbye and thanks for all the fish!

OWNERS: remove arithx

---

kola-denylist.yaml

See: https://bugzilla.redhat.com/show_bug.cgi?id=1986239

kola-denylist: disable crio.base tests for all arches

---

ci/build-test-qemu.sh
manifest.yaml
rhcos-packages.yaml
tests/kola/misc-ro/misc-ro.sh

This includes some smaller cherry-picked fixes from 4.8.

Bug 1987276: [release-4.7] Move 4.7 to RHEL 8.4

---

docs/faq.md

Motivated by private chat asking about the kernel version.

FAQ: Note that we expose some key package versions via metadata

---

tests/kola/misc-ro/misc-ro.sh

Add test to verify that rhaos package versions match the OpenShift
version.

test: add test to check rhaos package versions

---

OWNERS

Hi, I'm a new member of the CoreOS team.

Grant peberanek necessary permissions

---

OWNERS

Hello, I added my username to the owners file to obtain permissions to run tests and do operations with OpenShift run bots.

Added a user to the Owners file

---

docs/development.md

I found myself doing this today and figured it was useful for others.

docs: add instructions for using cosa in app.ci

---

kola-denylist.yaml

These are still problems and need to be extended.

denylist: extend snoozes

---

README.md
docs/openshift-ci-notes.md

This documents the changes introduced by https://github.com/openshift/release/pull/26517
I wasn't sure where to put this info. I thought it should probably live here since it concerns this repository's CI configuration. However, I'm open to suggestions.

docs: adds periodic job docs

---

kola-denylist.yaml

Add ppc64le tests in kola-denylist

---

tests/kola/files/env-godebug

See:
- https://bugzilla.redhat.com/show_bug.cgi?id=1886134
- https://github.com/openshift/os/pull/441

Add test: verify environment variable `GODEBUG=x509ignoreCN=0` in initrd

---

image.yaml

Update to hardware version 15 and switch the OS ID from RHEL 7 to 64-bit RHEL 8.
For https://github.com/coreos/coreos-assembler/pull/2762.

image: specify VMware OS and HW versions

---

tests/layering/build_helper_test.go

As I work on getting this test to run in Prow, I realized this is not an obvious name for this environment variable.

layering_test: BASE_IMAGE_TAG is a better name

---

ci/derived-image-test.sh

When we log into the main CI cluster to get our registry credentials, the kubeconfig is mutated with the addition of the CI cluster context. Thus, when we try to run the derived OS tests against it, we get an HTTP 403. This grabs the name of the test cluster context and switches to it after we obtain our registry creds.

ci: remember test cluster context

---

OWNERS

Petr has left the team.
This reverts commit 832d23f77292c8a3165f443bcf8157e04429fa41.

Revert "Grant peberanek necessary permissions"

---

docs/faq.md

- Describe how to change Kernel packages in RHCOS

faq: Add how to for Kernel change

---

OWNERS

Adding myself (Github: RishabhSaini) to OWNERS/approvers as a part of onboarding in the CoreOS team

Adding RishabhSaini to OWNERS

---

ci/Dockerfile.cosa-build
ci/Dockerfile.cosa-oci-archive
ci/Dockerfile.layering-test
ci/Dockerfile.machine-os-oci-content
ci/test-qemu-firmware-uefi.sh
ci/test-qemu-kola-upgrade.sh
ci/test-qemu-kola.sh
ci/test-qemu-metal.sh
ci/test-qemu-nvme.sh

Moves the Dockerfiles and test scripts from the openshift/release repo.

moves scripts and Dockerfiles into os repo

---

ci/prow-build-test-qemu.sh

This is what we have on main.
Closes: https://github.com/openshift/os/issues/843

[release-4.11] ci: Fetch RHEL 8.6

---

OWNERS

Add jschintag to OWNERS

---

docs/faq.md

- add a section about multipath on secondary disks
- separate out question about changing multipath settings
- mention that configuration should be done via Ignition/MC
- mention `/etc/multipath/conf.d`
- use `rpm-ostree initramfs-etc` now that it's stable
- explain `rw` karg
- add a section about iSCSI support

faq: add more info about multipathing

---

OWNERS

Modified content as instructed by provided documentation.

OWNERS: Add Adam Piasecki (c4rt0)

---

README.md
docs/development-scos.md
docs/development.md
manifest-rhel-8.6.yaml
manifest-rhel-9.0.yaml

Initial set of docs for SCOS with current workarounds.
I'll also update the RHCOS docs to match.

docs: Add instructions to build & test SCOS

---

docs/development-rhcos.md
docs/development-scos.md

The objective here is to make this guide canonical and "remove" the internal doc.

docs: Update build & test guides

---

OWNERS

Signed-off-by: Clement Verna <cverna@tutanota.com>

OWNERS: remove Saqib Ali from the owners file

---

ci/prow-entrypoint.sh

This should work now that we have https://github.com/openshift/os/issues/954

ci: Enable all metal kola tests for SCOS

---

extensions/Dockerfile

Not sure this'll work/
/cc @travier 
/cc @lmzuccarelli

extensions: Enable SCOS extension builds with COSA

---

common.yaml

Signed-off-by: Peter Hunt <pehunt@redhat.com>

add conmon-rs to RHCOS

---

common.yaml

Fixes: https://github.com/openshift/os/issues/1003

Remove docs and some known broken symlinks

---

common-el9.yaml

Closes: https://github.com/openshift/os/issues/942

common-el9: Make nvmf dracut script executable

---

kola-denylist.yaml

denylist: Add ext.config.rpm-ostree.replace-rt-kernel

---

kola-denylist.yaml

See: https://github.com/openshift/os/issues/942

kola-denylist: Drop fixed tests from list

---

ci/prow-entrypoint.sh
overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fde/module-setup.sh
overlay.d/05rhcos/usr/libexec/coreos-cryptfs
overlay.d/25rhcos-azure-udev/usr/lib/dracut/modules.d/25rhcos-azure-udev/module-setup.sh
tests/kola/rebuild-selinux-policy/test.sh
tests/kola/rpm-ostree/replace-rt-kernel

See: https://github.com/coreos/fedora-coreos-tracker/issues/1180
Added manually here (and not via the repo templates) as I don't think the bot has the right to make a pull request here (?)
Edit: Not sure the GitHub workflow run here. We'll likely have to adapt this one for Prow

github: Add ShellCheck workflow

---

docs/faq.md

This came up this morning in chat.

faq: add entry about extensions RPMs

---

kola-denylist.yaml

See https://github.com/openshift/os/issues/1149

kola: Denylist `luks.*` on ppc64le

---

kola-denylist.yaml

Verify https://bugzilla.redhat.com/show_bug.cgi?id=2111069 is fixed and fixed version is `selinux-policy-34.1.39-1.el9`

denylists: enable networking tests

---

docs/faq.md

It's easy and straightforward now!

faq: Document how to upgrade now outside of a cluster

---

kola-denylist.yaml

denylist: Extend luks to s390x

---

kola-denylist.yaml

denylist: Skip ext.config.shared.ignition.resource.remote

---

docs/faq.md

faq: Document current floating tags

---

kola-denylist.yaml

See https://github.com/openshift/os/issues/1213

denylist: Add `ext.config.shared.multipath.multipathd-service-fix`

---

docs/development-rhcos.md

See: https://github.com/coreos/coreos-assembler/pull/3417

docs/rhcos: Update for new COSA feature

---

docs/faq.md

faq: Document running container directly for inspection

---

tests/kola/ssh/config
tests/kola/ssh/data/commonlib.sh

See: https://github.com/openshift/os/pull/1251
See: https://github.com/openshift/os/issues/1216
See: https://issues.redhat.com/browse/OCPBUGS-11764

tests: Add OpenSSH config test

---

tests/kola/afterburn/platform-id

This is based on https://github.com/coreos/coreos-assembler/pull/3424

tests: change platform id `gce` to `gcp`

---

tests/kola/afterburn/platform-id
tests/kola/afterburn/sshkey-service
tests/kola/console/console-login-helper-service
tests/kola/disk/iscsi-initiatorname-service
tests/kola/disk/nvme-compat-symlink
tests/kola/files/check-qemu-ga
tests/kola/files/conntrack-tools
tests/kola/files/env-godebug
tests/kola/files/kata-osbuilder
tests/kola/files/localtime
tests/kola/files/trust-cpu
tests/kola/files/usrlocal-fixup
tests/kola/rebuild-selinux-policy/test.sh
tests/kola/rpm-ostree/replace-rt-kernel
tests/kola/rpm-ostree/startlimit
tests/kola/ssh/config
tests/kola/systemd/journal-compat
tests/kola/version/drop-azure-ptp
tests/kola/version/rhaos-pkgs-match-openshift
tests/kola/version/rhel-major-version
tests/kola/version/rhel-matches-rhcos-build

This based on https://github.com/coreos/coreos-assembler/pull/3425

tests: add `description` for tests

---

ci/prow-entrypoint.sh
manifest-rhel-9.2.yaml

I didn't have permission to add on top of https://github.com/openshift/os/pull/1289, so this PR encompasses @HuijingHei's changes as well as fixes to CI.  See individual commits for more details.
https://github.com/openshift/release/pull/39586 would also fix CI but the cleanup here is needed regardless.

Fix prow CI errors for RHCOS jobs

---

ci/prow-entrypoint.sh

See https://github.com/openshift/release/pull/39361

ci: enable ci tests as we have updated to RHEL 9.2 GA repos

---

OWNERS

as part of my onboarding process :)

add jbtrystram as an approver

---

overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/module-setup.sh
overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips-dracut-boot-fix.service
overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips-finish.service
overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips.sh

Backport of #1332, #1356, #1362

OCPBUGS-23907: Enable FIPS in live ISO

---

docs/faq.md

NO-JIRA: faq: Doc how to mount `coreos-luks-root-nocrypt`

---

docs/faq.md

This comes up often enough that it's worth elaborating.

NO-JIRA: faq: add more details and examples for kernel <--> kernel-rt

---

docs/faq.md

Fixes 237b3ec ("faq: add more details and examples for kernel <-->
kernel-rt").

NO-JIRA:  faq: fix kernel-rt-modules-extra uninstall and mention kernel-64k

---

docs/faq.md

Fixes f9fb2c6 ("faq: add details about RAID installations").

NO-JIRA: docs/faq.md: fix typo in /dev/md/imsm0 path

---

docs/faq.md

We now support booting from iSCSI. Expand on the different options there.

NO-JIRA:docs/faq.md: update iSCSI-related bits

---

tests/kola/version/rhaos-pkgs-match-openshift

See: https://github.com/openshift/os/issues/1427

COS-2613: kola: fix rhaos-pkgs-match-openshift

---

extensions/Dockerfile

[release-4.13] NO-JIRA: extensions/Dockerfile: bump builder to f40

---

extensions/Dockerfile

[release-4.12] NO-JIRA: extensions/Dockerfile: bump builder to f40

---

docs/faq.md

This came up recently.
While we're here, also just bump the example to something more recent.

NO-JIRA: faq: include information about how to query openshift/os commit for release

---

Containerfile

I think at the time I wrote this, I hadn't set up the pipeline yet for it, so I wasn't sure what its tag name was going to me. We know it now, so just fix this.

NO-JIRA: Containerfile: use correct tag in FROM

---

extensions/Dockerfile

See: https://github.com/coreos/fedora-coreos-tracker/issues/1695

NO-JIRA: extensions/Dockerfile: Update to Fedora 41

---

kola-denylist.yaml

See: https://github.com/coreos/fedora-coreos-tracker/issues/1849

NO-JIRA: denylist: add ext.config.shared.rpm-ostree.kernel-replace

---

overrides-c9s.yaml

Manual cherry-pick of #1675 due to merge conflict

[release-4.17]:NO-JIRA: Remove clevis overrides for OKD

---

extensions-ocp-rhel-9.6.yaml
extensions-okd-c9s.yaml

Additional tracker: https://issues.redhat.com/browse/OCPEDGE-1418

COS-3063: Adding the needed packages for Kubesan and the kSAN Storage Operator

---

c9s.repo

To pickup the latest cri-o, conmon and tools

NO-JIRA:OKD: Move sig-cloud to 4.19

---

kola-denylist.yaml

See: https://github.com/openshift/os/issues/1673

NO-JIRA: kola-denylist: drop ext.config.shared.rpm-ostree.kernel-replace

---

README.md

This is a simple diagram of the node image and what it's made up of.

NO-JIRA: README.md: add Mermaid diagram

---

docs/faq.md

This keeps coming up, so let's add that here.
Also update some of the examples to use newer releases, and stop mentioning directly digging into `commitmeta.json` in the pipeline S3 bucket.

NO-JIRA: faq: add info about querying rpmdb and extensions

---

OWNERS

NO-JIRA: Add PeaceRebel (Bipin) to approvers list
